version: "3.7"
services:
  toolloaner:
    container_name: tl_public
    build:
      context: .
      # dockerfile: dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL = http://localhost:8010/api/v2
      - NODE_ENV=development
    env_file:
      - ./.env.local
